---
- name: Deploy Flask App and PostgreSQL DB
  hosts: db_server, app_server
  become: true
  vars:
    # Base path for the application deployment
    app_base_path: /opt/flask-app
  roles:
    - role: postgresql
      tags: db
      # Only run this role on the db_server group
      when: inventory_hostname in groups['db_server']
    - role: python-flask
      tags: app
      # Only run this role on the app_server group
      when: inventory_hostname in groups['app_server']
    - role: flask-deploy
      tags: app
      # Only run this role on the app_server group
      when: inventory_hostname in groups['app_server']