[g1]
App_server ansible_host=172.31.26.30 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/Arsenal.pem ansible_ssh_common_args='-oStrictHostKeyChecking=no'
DB_server ansible_host=172.31.18.4 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/Arsenal.pem ansible_ssh_common_args='-oStrictHostKeyChecking=no'
