---
- name: Install PostgreSQL
  become: true
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is enabled and running
  become: true
  service:
    name: postgresql
    state: started
    enabled: true

- name: Locate pg_hba.conf
  become: true
  find:
    paths: /etc/postgresql
    patterns: pg_hba.conf
    recurse: yes
  register: pg_hba

- name: Allow local connections in pg_hba.conf
  become: true
  lineinfile:
    path: "{{ pg_hba.files[0].path }}"
    regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32\s+\w+'
    line: 'host all all 127.0.0.1/32 trust'
    backrefs: yes
  when: pg_hba.matched > 0
  notify: Restart postgresql